apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-replicaset
  labels:
    a: america     
spec:
  replicas: 4
  selector:
    matchLabels:
        a: america
  template:
    metadata:
      labels:
        a: america
    spec:
      containers:
      - name: nginx
        image: tomcat:8
        envFrom:
        - secretRef:
           name: secret-1
        ports:
        - containerPort: 80
